name: wordpress-desktop
version: latest
version-script: cat $SNAPCRAFT_STAGE/version
summary: WordPress.com Desktop client
description: |
 A desktop app that gives WordPress a permanent home in your dock.
 .
 Write and design with no other browser tabs to distract you. Switch
 easily between managing your WordPress sites and your favorite desktop
 apps.
 .
 The WordPress.com desktop app will scale to any size. Do you need a
 small window on the side to keep your eye on notifications, or do want
 to expand to a truly full screen for a zen writing experience? Take
 your pick.

grade: stable
confinement: strict

architectures:
  - build-on: amd64

parts:
  wordpress-desktop:
    plugin: dump
    source: https://public-api.wordpress.com/rest/v1.1/desktop/linux/download?type=deb
    source-type: deb
    override-build: |
      DEB_API="https://public-api.wordpress.com/rest/v1.1/desktop/linux/download?type=deb"
      echo $DEB_API
      VERSION=$(curl -IXGET -s  $DEB_API | grep -i Content-Disposition | awk -F '"' '{print $2}' | awk -F '-' '{print $4}' | awk -F '.' '{print $1,$2,$3}' | tr ' ' '.')
      echo "Version: $VERSION"
      echo $VERSION > $SNAPCRAFT_STAGE/version
      snapcraftctl build
    after:
      - desktop-gtk2
    build-packages:
      - curl
    stage-packages:
      - libasound2
      - libgconf-2-4
      - libnotify4
      - libnspr4
      - libnss3
      - libpulse0
      - libxss1
      - libxtst6

apps:
  wordpress-desktop:
    command: bin/desktop-launch $SNAP/opt/WordPress.com/wpcom
    desktop: usr/share/applications/wpcom.desktop
    # Correct the TMPDIR path for Chromium Framework/Electron to ensure
    # libappindicator has readable resources.
    environment:
      TMPDIR: $XDG_RUNTIME_DIR
    plugs:
      - browser-support
      - desktop
      - desktop-legacy
      - gsettings
      - home
      - mount-observe
      - network
      - opengl
      - pulseaudio
      - unity7
      - wayland
      - x11
